export const autoFilledData = {
    title: 'OUMAIMA Abdou',
    post_title: 'Software Engineer',
    nom: 'OUMAIMA',
    prenom: 'ABDOU',
    profile_image_source: '/images/profile.png',
    email: 'oumaima@gmail.com',
    phone: '+212555555',
    adress: 'Rabat',
    age: '23',
    summary: "On sait depuis longtemps que travailler avec du texte lisible et contenant du sens est source de distractions, et empêche de se concentrer sur la mise en page elle-même. L'avantage du Lorem Ipsum sur un texte générique comme 'Du texte. Du texte. Du texte.' est qu'il possède une distribution de lettres plus ou moins normale, et en tout cas comparable avec celle du français standard. De nombreuses suites logicielles de mise en page ou éditeurs de sites Web ont fait du Lorem Ipsum.",
    experience: [
        {
            title: 'Frontend Developer',
            company_name: 'Capgemini',
            city: 'RABAT',
            start_date: '2022',
            end_date: '2023',
            description: "Plusieurs variations de Lorem Ipsum peuvent être trouvées ici ou là, mais la majeure partie d'entre elles a été altérée par l'addition d'humour ou de mots aléatoires qui ne ressemblent pas une seconde à du texte standard.",
            tasks: ["Build interfaces", "Fix bugs"],
        },
        {
            title: 'Backend Developer',
            company_name: 'Orange',
            city: 'CASA',
            start_date: '2021',
            end_date: '2022',
            description: "Plusieurs variations de Lorem Ipsum peuvent être trouvées ici ou là, mais la majeure partie d'entre elles a été altérée par l'addition d'humour ou de mots aléatoires qui ne ressemblent pas une seconde à du texte standard.",
            tasks: [],
        },
        {
            title: 'Full Stack Developer',
            company_name: 'Inwi',
            city: 'Mohammedia',
            start_date: '2020',
            end_date: '2021',
            description: "Plusieurs variations de Lorem Ipsum peuvent être trouvées ici ou là, mais la majeure partie d'entre elles a été altérée par l'addition d'humour ou de mots aléatoires qui ne ressemblent pas une seconde à du texte standard.",
            tasks: ["Contrairement à une opinion répandue", "Contrairement à une opinion répandue"],
        }
    ],
    projects: [
        {
            title: 'Chatbot',
            type: 'Open Source',
            description: "Tous les générateurs de Lorem Ipsum sur Internet tendent à reproduire le même extrait sans fin, ce qui fait de lipsum.",
        },
        {
            title: 'To do list',
            type: 'Open Source',
            description: "Tous les générateurs de Lorem Ipsum sur Internet tendent à reproduire le même extrait sans fin, ce qui fait de lipsum. Tous les générateurs de Lorem Ipsum sur Internet tendent à reproduire le même extrait sans fin, ce qui fait de lipsum.",
        },
    ],
    education: [
        {
            title: 'MSc in Computer Science',
            etablissement: 'University College London',
            city: 'London',
            start_date: '2016',
            end_date: '2018',
            description: 'Tous les générateurs de Lorem Ipsum sur Internet tendent.Tous les générateurs de Lorem Ipsum sur Internet tendent',
        },
        {
            title: 'BSc Maths and Physics',
            etablissement: 'Imperial College London',
            city: 'London',
            start_date: '2018',
            end_date: '2021',
            description: 'Tous les générateurs de Lorem Ipsum sur Internet tendent.',
        }
    ],
    hardSkills: [
        { name: 'JavaScript/React', level: 3 },
        { name: 'Python/Ruby/PHP', level: 2 },
        { name: 'Node.js/ASP.NET', level: 5 },
        { name: 'PostgreSQL/MySQL', level: 4 },
    ],
    softSkills: [
        { name: 'Effective communication', level: 3 },
        { name: 'Team player', level: 4 },
        { name: 'Strong problem solver', level: 5 },
        { name: 'Good time management', level: 4 },
    ],
    languages: [
        { name: 'French', level: 4 },
        { name: 'English', level: 4 },
        { name: 'Spanish', level: 2 },
    ],
    awards: [
        { name: 'Award Lorem Ipsum', source: 'Microsoft lorem ipsum (2023)' },
        { name: 'Award Donec Sodales', source: 'Oracle Aenean (2020)' },
    ],
    interests: [
        { name: 'Climbing' },
        { name: 'Snowboarding' },
        { name: 'Photography' },
        { name: 'Travelling' },
    ],
}

export const emptyData = {
    title: '',
    post_title: '',
    nom: '',
    prenom: '',
    profile_image_source: '',
    email: '',
    phone: '',
    adress: '',
    age: '',
    summary: '',
    experience: [],
    projects: [],
    education: [],
    hardSkills: [],
    softSkills: [],
    languages: [],
    awards: [],
    interests: [],
}